language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- python setup.py sdist bdist_wheel
- python -m pip install dist/wheelie-*.tar.gz --ignore-installed --no-deps
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: docfast
  password:
    secure: WT9Rjff2iV2NqSLIveteMdebAbnPuHXnkOhURQGYUJX7zSasUXNJrmMw7zysxuIDRCQyyHSe5p6lHwKatbyI9eHZyyQ59YbnkyKGM3iYtygPofHQ+D/rKwl6BRK1BiHduUHHbyj4zvfNkIekMzasoLFvKsdro+1oymOwJVzFWHs2OYV3ovgVt0LZ5kpjTF0qj+oyMLJrLGKa/JsJFR1eBaEW8ZAbe4WJIKXGG1h1GG7dMXVZLdtRwpj+9RwfghiQJFfX4Uc9PqphoykfJ6C1x7xSZdeJHZ0DvK+tDItxVLDkK9DF0wfgMIrChN19EVdSJagD7q6E30qlVCy7DzWO3+T0lgP6JaMCo5deQzgNgaPAV4y1f5k0U8od7rwrxqIiA/X2O2jgK7U/QEfGLtL26TBeHdtkETLUACwWdfIcDP9tQcPr0vE7pD/dtQOrMXOH/lFBE4bYe1iC9sQPzSIc0a9RL0kwLnj7v7ahKm8Vz07Mjk3MQdmx36C3pXCC/ZbHTJbXSEAYg4cbIgdJY1oAuZA/SXiJpOdAXow3CS8ss/8KQIV7sHmHePjks95qsU+tMydUHuv8MZZbKhpqURe/GUh3WWVv3BTIwIHLHAqmIsnUVqHPd05XTtfr7FgWjE8DUzF5Vz1w1gPxtqiAW0HeRICrdnIbSxFVwV4vxfUIF30=
  skip_cleanup: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: deathbeds/wheelie
    python: '3.6'
